out_dir: results
dataset:
  format: PyG
  name: chrome-run-01-without-centrality-metrics
  dir: ./webgraphs/Chrome
  task: node
  task_type: classification
  transductive: true
  split:  [0.8, 0.1, 0.1] # train, val, test
  transform: none
train:
  batch_size: 128
  eval_period: 20
  ckpt_period: 100
  sampler: full_batch
model:
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 2
  layers_mp: 3
  layers_post_mp: 1
  dim_inner: 64
  layer_type: sageconv
  stage_type: skipsum
  batchnorm: true
  act: prelu
  dropout: 0.1
  agg: mean
  skip_every: 0
  normalize_adj: false
  self_msg: none
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 200